"""empty message

Revision ID: 0025297f4d82
Revises: 2eba0df4ff19
Create Date: 2026-02-27 23:53:33.667410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0025297f4d82'
down_revision = '2eba0df4ff19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runners', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
