"""empty message

Revision ID: 177a7c003247
Revises: 4c35f983fb65
Create Date: 2026-02-28 17:18:05.671035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177a7c003247'
down_revision = '4c35f983fb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strava_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strava_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strava_token_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strava_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strava_token_user_id'))

    op.drop_table('strava_token')
    # ### end Alembic commands ###
