"""empty message

Revision ID: 4c35f983fb65
Revises: 
Create Date: 2026-02-25 23:44:35.726159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c35f983fb65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('runner', 'mentor', name='role_types'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorited_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorited_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_expiry'), ['expiry'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_user_id'), ['user_id'], unique=False)

    op.create_table('streak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streak_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['streak_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streak')
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_expiry'))

    op.drop_table('password_reset')
    op.drop_table('favorites')
    op.drop_table('user')
    op.drop_table('runners')
    # ### end Alembic commands ###
