"""empty message

Revision ID: 84ec3531a073
Revises: 5181bc0d6409
Create Date: 2026-02-21 02:29:48.900096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84ec3531a073'
down_revision = '5181bc0d6409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_by_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('years_running', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('schedule', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_mentor', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_by_id'], ['id'])
        batch_op.drop_column('role')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    with op.batch_alter_table('runners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('runner', 'mentor', name='role_types'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_mentor')
        batch_op.drop_column('location')
        batch_op.drop_column('schedule')
        batch_op.drop_column('years_running')
        batch_op.drop_column('user_by_id')

    # ### end Alembic commands ###
