"""empty message

Revision ID: 91793317de82
Revises: cfdfcca323ef
Create Date: 2026-02-14 00:08:59.575334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91793317de82'
down_revision = 'cfdfcca323ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorited_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorited_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streak_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['streak_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streak')
    op.drop_table('favorites')
    # ### end Alembic commands ###
